/* =====================================================================
   DICIONÁRIO DE PALAVRAS ACEITAS
   =====================================================================
   Toda tentativa do aluno precisa estar nesta lista (ou ser uma das
   palavras do dia — essas são adicionadas automaticamente pelo jogo).

   Mistura de vocabulário de Python/dados com português comum, para o
   jogo não ficar impossível.

   Pode escrever com ou sem acento: o jogo normaliza tudo.
   Entradas que não tenham exatamente 5 letras são ignoradas
   silenciosamente, então não há risco de quebrar o jogo.
   ===================================================================== */

const DICIONARIO = [
  // ---------- Python / programação / dados ----------
  'LISTA','TUPLA','CLASS','PRINT','INPUT','WHILE','BREAK','FLOAT','RANGE','INDEX',
  'SLICE','MERGE','DEBUG','STACK','QUEUE','ARRAY','BYTES','SCOPE','YIELD','ASYNC',
  'AWAIT','FALSE','ERROR','RAISE','QUERY','TOKEN','PARSE','CACHE','MODEL','NUMPY',
  'PANDA','FLASK','BLACK','PATCH','BUILD','WHEEL','SHELL','TUPLE','LOOPS','SETUP',
  'BATCH','TRAIN','SCORE','SPLIT','MEDIA','MEDIO','MODAS','MODULO','CODIGO','DADOS',
  'CHAVE','VALOR','LINHA','TEXTO','TIPOS','NIVEL','PILHA','GRUPO','CAMPO','TESTE',
  'CLASSE','LACOS','VETOR','FILTRO','FUNCAO','LOCAL','GLOBAL','CLONE','FORKS','PUSH',

  // ---------- Português comum (5 letras) ----------
  'AMIGO','AMPLO','ANDAR','ANIMO','ANTES','APOIO','ARDOR','AREIA','ARROZ','ASSIM',
  'ATIVO','AUDIO','AVISO','BAIXO','BANCO','BARCO','BEBER','BOLSA','BONDE','BRAVO',
  'BRISA','BUSCA','CAIXA','CALMA','CAMPO','CANAL','CANTO','CARGO','CARRO','CARTA',
  'CASAL','CASAS','CAUSA','CEDER','CERTO','CHEIO','CHUVA','CICLO','CINCO','CLARO',
  'COBRA','COLAR','COMER','CONTA','CORPO','CORTE','COSTA','CRIAR','CURSO','CUSTO',
  'DENTE','DIGNO','DOBRO','DOCES','DUPLA','DURAR','ELEVA','ENTRE','ERRAR','ESTAR',
  'FALAR','FALHA','FAZER','FESTA','FICAR','FILHO','FOGOS','FOLHA','FORCA','FORMA',
  'FRACO','FRUTA','FUNDO','GANHO','GATOS','GELOS','GOSTO','GRAUS','GRITO','HORAS',
  'IDEIA','IGUAL','JOGAR','JOVEM','JULHO','JUNTO','LARGO','LEITE','LENTO','LETRA',
  'LEVAR','LIMPO','LIVRO','LONGE','LUGAR','LUTAR','MAIOR','MARCA','MEDIR','MEIOS',
  'MENOR','MESAS','METAL','METRO','MOLHO','MORAR','MOTOR','MOVER','MUITO','MUNDO',
  'NADAR','NEGRO','NOBRE','NOITE','NORMA','NOVOS','NUVEM','OBRAS','OLHAR','ONDAS',
  'ORDEM','OUTRO','OUVIR','PAGAR','PAPEL','PARAR','PARTE','PASSO','PEDIR','PEDRA',
  'PEIXE','PENSA','PERDA','PESAR','PISTA','PLANO','PLENO','PODER','POETA','PONTE',
  'PONTO','PORTA','POUCO','PRAIA','PRAZO','PRECO','PRESO','PRETO','PRIMO','PROVA',
  'PULAR','QUASE','QUEDA','QUERO','RADIO','RAIVA','RAMOS','RAZAO','REDES','REGRA',
  'REINO','RENDA','RESTO','ROCHA','RODAS','ROSTO','ROUPA','RUIDO','SABER','SABOR',
  'SAIDA','SALAS','SALTO','SANTO','SAUDE','SECAR','SEGUE','SELVA','SENDO','SENTE',
  'SERIE','SERVE','SETOR','SIGLA','SINAL','SITES','SOBRE','SOCIO','SOLTO','SONHO',
  'SORTE','SUAVE','SUBIR','SUJOS','SUPER','TARDE','TEIAS','TELAS','TEMAS','TEMPO',
  'TENDA','TERRA','TIRAR','TOCAR','TODOS','TOMAR','TORRE','TOTAL','TRACO','TRAJE',
  'TRATO','TREVO','TRIGO','TROCA','TURMA','UNIAO','USUAL','VAGAS','VALER','VAPOR',
  'VARIA','VAZIO','VELHO','VENDA','VENTO','VERBO','VERDE','VIAJA','VIDAS','VIDRO',
  'VIGOR','VINHO','VIRAR','VISAO','VITAL','VIVER','VOCES','VOLTA','VOTAR','ZEBRA',
  'ZONAS','ABRIR','ACHAR','AGORA','AINDA','ALGUM','ALTOS','AMBOS','APOS','AQUI',
  'BAIRRO','BELEZA','BOLAS','BRAÇO','CABEÇA','CAFES','CALOR','CAMAS','CANTA','CARNE',
  'CHEFE','CHUTE','CIDADE','CLIMA','COISA','COMUM','CONTO','COURO','CRISE','CULPA',
  'CURVA','DEIXA','DEPOIS','DIZER','DOBRA','DOENTE','DORME','DUVIDA','EIXOS','ELOGIO',
  'ENVIA','EQUIPE','ESCOLA','ESPÉCIE','EXATO','FACIL','FALTA','FAMA','FAROL','FATOR',
  'FEBRE','FEIRA','FERRO','FIBRA','FILME','FINAL','FIRME','FLUXO','FOCOS','FOGAO',
  'FONTE','FORNO','FRASE','FRENTE','FRIOS','FUGIR','FUMAR','FUROS','GARFO','GELO',
  'GENTE','GESTO','GIRAR','GLOBO','GOLPE','GRAMA','GRAVE','GUERRA','HABIL','HAVER',
  'HOMEM','HONRA','HOTEL','HUMOR','IMAGEM','INDIO','INICIO','INTER','IRMAO','ITENS',
  'JANTA','JOGOS','JORNAL','JUIZO','JUSTO','LADOS','LAGOA','LANCE','LAPIS','LAUDO',
  'LEGAL','LEMBRA','LEOES','LIDER','LIGAR','LIMAO','LIMITE','LINDO','LISOS','LOBOS',
  'LOJAS','LOUCO','LUCRO','LUVAS','MADRE','MAGRO','MALAS','MANGA','MANHA','MAPAS',
  'MARES','MASSA','MATAR','MEDAL','MELAO','MENOS','MENTE','MESES','MISTO','MOEDA',
  'MOLDE','MONTE','MORAL','MORTE','MOSCA','MUROS','MUSEU','NAVIO','NEVOA','NINHO',
  'NOMES','NOTAS','NUVENS','OBTER','OCEANO','OCUPA','OLHOS','OMBRO','OPCAO','OURO',
  'OVOS','PACTO','PADRE','PAIXAO','PALCO','PALMA','PANOS','PARTO','PATIO','PATOS',
  'PAUSA','PEDAL','PEITO','PENAS','PERTO','PESCA','PESOS','PIANO','PICOS','PINTA',
  'PIRES','PLACA','PLUMA','POBRE','POCOS','POEMA','POLVO','POMBO','PORCO','POSSE',
  'POSTO','PRATO','PREGO','PRESA','PRISMA','PULSO','PUROS','QUEDAS','QUEIXO','RAIOS',
  'RAMPA','RATOS','REGIAO','REMAR','REMOS','RENAL','RESMA','RETAS','REVER','RIMAS',
  'RITMO','RIVAL','ROBOS','ROLAR','ROSAS','ROTAS','RUAS','RUBRO','RUGAS','RUMOS',
  'SACOS','SALAO','SALSA','SANGUE','SAPOS','SEGUR','SELOS','SEMEA','SENAO','SETAS',
  'SILVA','SIMPLES','SISTEMA','SOBRA','SOFRE','SOLAR','SOLOS','SOMAR','SONDA','SOPRO',
  'SORRI','SUCOS','SUJAR','SULCO','TABUA','TACOS','TALHO','TAMPA','TANQUE','TAPAS',
  'TECLA','TECTO','TEMOR','TENIS','TENSO','TERCO','TERMO','TESES','TIGRE','TIMES',
  'TINTA','TIROS','TOALHA','TOCHA','TONEL','TOPOS','TORTA','TOSSE','TRAVA','TREMO',
  'TRENO','TRIBO','TRIPA','TRONO','TROPA','TUBOS','TUNEL','TURNO','ULTIMO','UNHAS',
  'URNAS','URSOS','USINA','UTEIS','VACAS','VAGAO','VALAS','VARAS','VASOS','VEIAS',
  'VELAS','VENCE','VERAO','VERSO','VESTE','VIGAS','VILAS','VINCO','VINTE','VIRUS',
  'VISTA','VIVOS','VOGAL','VOLTS','VULTO','XAROPE','ZELOS','ZEROS',
];
